apiVersion: v1
kind: Secret
metadata:
  name: ipsec-secrets
  labels:
    app: ipsec-anomaly-system
type: Opaque
# stringData allows us to write plain text; Kubernetes will base64 encode it internally
stringData: 
  # AWS Aurora endpoint or in-cluster Postgres service name
  DATABASE_URL: "postgres://admin:password@postgres-service.default.svc.cluster.local:5432/ipsec"
  # AWS ElastiCache endpoint or in-cluster Redis service name
  REDIS_URL: "redis-master.default.svc.cluster.local:6379"